services:
  app:
    build: .
    container_name: myapp_backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/myapp
      - IS_DOCKER=true
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: myapp_mysql
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql

