import type { Express } from "express";
import { logger } from "../core/logger/logger.js";
import authRouter, { path as authPath } from "../modules/auth/auth.routes.js";
import userRouter, { path as userPath } from "../modules/user/user.routes.js";
import roleRouter, { path as rolePath } from "../modules/roles/role.routes.js";
import permissionRouter, { path as permissionPath } from "../modules/permissions/permission.routes.js";
import rbacRouter, { path as rbacPath } from "../modules/rbac/rbac.routes.js";
import productRouter, { path as productPath } from "../modules/product/product.routes.js";
import optionsRouter from "./options.routes.js";
import { adminBidangFokusRouter } from "../modules/bidangfokus/bidangfokus.routes.js";
import outputRouter, { path as outputPath } from "../modules/output/output.routes.js";
import { adminProdiRouter } from "../modules/prodi/prodi.routes.js";
import sertifikatMutuRouter, {
  path as sertifikatMutuPath,
} from "../modules/sertifikatmutu/sertifikatmutu.routes.js";
import { adminSkemaRouter } from "../modules/skema/skema.routes.js";
import tahunAkademikRouter, {
  path as tahunAkademikPath,
} from "../modules/tahunakademik/tahunakademik.routes.js";
import filesRouter, { path as filesPath } from "../modules/files/files.routes.js";
import uploadRouter, { path as uploadPath } from "../modules/upload/upload.routes.js";
import beritaRouter, { path as beritaPath } from "../modules/berita/berita.routes.js";
import pengumumanRouter, { path as pengumumanPath } from "../modules/pengumuman/pengumuman.routes.js";
import panduanRouter, { path as panduanPath } from "../modules/panduan/panduan.routes.js";
import publicpageRouter, { path as publicpagePath } from "../modules/publicpage/publicpage.routes.js";
import carouselRouter, { path as carouselPath } from "../modules/carousel/carousel.routes.js";
import landingSliderRouter, { path as landingSliderPath } from "../modules/landingslider/landingslider.routes.js";
import capaianRouter, { path as capaianPath } from "../modules/capaian/capaian.routes.js";
import kategoriPublikasiRouter, {
  path as kategoriPublikasiPath,
} from "../modules/kategoripublikasi/kategoripublikasi.routes.js";
import publikasiRouter, { path as publikasiPath } from "../modules/publikasi/publikasi.routes.js";
import mitraKerjaRisetRouter, {
  path as mitraKerjaRisetPath,
} from "../modules/mitrakerjariset/mitrakerjariset.routes.js";
import productRisetRouter, { path as productRisetPath } from "../modules/productriset/productriset.routes.js";
import penghargaanRisetRouter, {
  path as penghargaanRisetPath,
} from "../modules/penghargaanriset/penghargaanriset.routes.js";
import hibahInternalRouter, { path as hibahInternalPath } from "../modules/hibahinternal/hibahinternal.routes.js";
import proposalRouter, { path as proposalPath } from "../modules/proposal/proposal.routes.js";
import invitesRouter, { path as invitesPath } from "../modules/invites/invites.routes.js";
import notificationRouter, { path as notificationPath } from "../modules/notification/notification.routes.js";
import researchRouter, { path as researchPath } from "../modules/research/research.routes.js";
import pengabdianRouter, { path as pengabdianPath } from "../modules/pengabdian/pengabdian.routes.js";
import penelitianProposalRouter from "../modules/penelitian-proposal/penelitian-proposal.routes.js";
import pengabdianProposalRouter from "../modules/pengabdian-proposal/pengabdian-proposal.routes.js";
import jadwalProposalRouter from "../modules/jadwal-proposal/jadwal-proposal.routes.js";
import luaranProposalRouter from "../modules/luaran-proposal/luaran-proposal.routes.js";
import rabProposalRouter from "../modules/rab-proposal/rab-proposal.routes.js";
import searchAnggotaRouter, { path as searchAnggotaPath } from "../modules/search-anggota/search-anggota.routes.js";
import proposalReviewRouter, { path as proposalReviewPath } from "../modules/proposal-review/proposal-review.routes.js";
import laporanUsulanRouter, { path as laporanUsulanPath } from "../modules/laporan-usulan/laporan-usulan.routes.js";
import proposalFinalPdfRouter, { path as proposalFinalPdfPath } from "../modules/proposal-final-pdf/proposal-final-pdf.routes.js";
import officialSignaturesRouter, { path as officialSignaturesPath } from "../modules/official-signatures/official-signatures.routes.js";
import hkiRouter, { path as hkiPath } from "../modules/hki/hki.routes.js";
import hkiReviewRouter, { path as hkiReviewPath } from "../modules/hki-review/hki-review.routes.js";
import monevProposalRouter, { path as monevProposalPath } from "../modules/monevproposal/monevproposal.routes.js";
import monevInternalRouter, { path as monevInternalPath } from "../modules/monev-internal/monev-internal.routes.js";
import dashboardRouter, { path as dashboardPath } from "../modules/dashboard/dashboard.routes.js";
import adminDashboardRouter, { path as adminDashboardPath } from "../modules/admin-dashboard/admin-dashboard.routes.js";
import auditlogRouter, { path as auditlogPath } from "../modules/auditlog/auditlog.routes.js";
import bulkImportRouter, { path as bulkImportPath } from "../modules/bulk-import/bulk-import.routes.js";
import usulanRouter, { path as usulanPath } from "../modules/usulan/usulan.routes.js";

export async function loadRoutes(app: Express): Promise<void> {
  app.get("/api/", (_req, res) => {
    res.status(200).send("API PRPM");
  });

  app.use(`/api${authPath}`, authRouter);
  app.use("/api/users", authRouter);
  app.use(`/api${userPath}`, userRouter);
  app.use(`/api${rolePath}`, roleRouter);
  app.use(`/api${permissionPath}`, permissionRouter);
  app.use(`/api${rbacPath}`, rbacRouter);
  app.use(`/api${productPath}`, productRouter);
  app.use("/api", optionsRouter);
  app.use("/api/admin/prodi", adminProdiRouter);
  app.use("/api/admin/skema", adminSkemaRouter);
  app.use("/api/admin/bidang-fokus", adminBidangFokusRouter);
  app.use(`/api${tahunAkademikPath}`, tahunAkademikRouter);
  app.use(`/api${outputPath}`, outputRouter);
  app.use(`/api${sertifikatMutuPath}`, sertifikatMutuRouter);
  app.use(`/api${filesPath}`, filesRouter);
  app.use(`/api${uploadPath}`, uploadRouter);
  app.use(`/api${beritaPath}`, beritaRouter);
  app.use(`/api${pengumumanPath}`, pengumumanRouter);
  app.use(`/api${panduanPath}`, panduanRouter);
  app.use(`/api${publicpagePath}`, publicpageRouter);
  app.use(`/api${carouselPath}`, carouselRouter);
  app.use(`/api${landingSliderPath}`, landingSliderRouter);
  app.use(`/api${capaianPath}`, capaianRouter);
  app.use(`/api${kategoriPublikasiPath}`, kategoriPublikasiRouter);
  app.use(`/api${publikasiPath}`, publikasiRouter);
  app.use(`/api${mitraKerjaRisetPath}`, mitraKerjaRisetRouter);
  app.use(`/api${productRisetPath}`, productRisetRouter);
  app.use(`/api${penghargaanRisetPath}`, penghargaanRisetRouter);
  app.use(`/api${hibahInternalPath}`, hibahInternalRouter);
  app.use(`/api${proposalPath}`, proposalRouter);
  app.use(`/api${invitesPath}`, invitesRouter);
  app.use(`/api${notificationPath}`, notificationRouter);
  app.use(`/api${researchPath}`, researchRouter);
  app.use("/api/usulan-penelitian", researchRouter);
  app.use(`/api${pengabdianPath}`, pengabdianRouter);
  app.use("/api/usulan-pengabdian", pengabdianRouter);
  app.use("/api/proposals/:id/penelitian", penelitianProposalRouter);
  app.use("/api/proposals/:id/pengabdian", pengabdianProposalRouter);
  app.use("/api/proposals/:id/jadwal", jadwalProposalRouter);
  app.use("/api/proposals/:id/luaran", luaranProposalRouter);
  app.use("/api/proposals/:id/rab", rabProposalRouter);
  app.use(`/api${searchAnggotaPath}`, searchAnggotaRouter);
  app.use(`/api${proposalReviewPath}`, proposalReviewRouter);
  app.use(`/api${laporanUsulanPath}`, laporanUsulanRouter);
  app.use(`/api${proposalFinalPdfPath}`, proposalFinalPdfRouter);
  app.use(`/api${officialSignaturesPath}`, officialSignaturesRouter);
  app.use(`/api${hkiPath}`, hkiRouter);
  app.use(`/api${hkiReviewPath}`, hkiReviewRouter);
  app.use(`/api${monevProposalPath}`, monevProposalRouter);
  app.use(`/api${monevInternalPath}`, monevInternalRouter);
  app.use(`/api${dashboardPath}`, dashboardRouter);
  app.use(`/api${adminDashboardPath}`, adminDashboardRouter);
  app.use(`/api${auditlogPath}`, auditlogRouter);
  app.use(`/api${usulanPath}`, usulanRouter);
  app.use(`/api${bulkImportPath}`, bulkImportRouter);

  logger.info(`Loaded Endpoint: /api${authPath}/register ============ Method: POST`);
  logger.info(`Loaded Endpoint: /api${authPath}/login =============== Method: POST`);
  logger.info(`Loaded Endpoint: /api${authPath}/me ================== Method: GET`);
  
  logger.info(`Loaded Endpoint: /api${userPath}/ =================== Method: GET`);
  logger.info(`Loaded Endpoint: /api${userPath}/:id ================ Method: GET`);
  logger.info(`Loaded Endpoint: /api${userPath}/ =================== Method: POST`);
  logger.info(`Loaded Endpoint: /api${userPath}/:id ================ Method: PATCH`);
  logger.info(`Loaded Endpoint: /api${userPath}/:id ================ Method: DELETE`);
  
  logger.info(`Loaded Endpoint: /api${rolePath}/ =================== Method: GET`);
  logger.info(`Loaded Endpoint: /api${rolePath}/:id ================ Method: GET`);
  logger.info(`Loaded Endpoint: /api${rolePath}/ =================== Method: POST`);
  logger.info(`Loaded Endpoint: /api${rolePath}/:id ================ Method: PUT`);
  logger.info(`Loaded Endpoint: /api${rolePath}/:id ================ Method: DELETE`);
  logger.info(`Loaded Endpoint: /api${rolePath}/:id/permissions ==== Method: PUT`);
  
  logger.info(`Loaded Endpoint: /api${permissionPath}/ ============= Method: GET`);
  logger.info(`Loaded Endpoint: /api${permissionPath}/:id ========== Method: GET`);
  logger.info(`Loaded Endpoint: /api${permissionPath}/ ============= Method: POST`);
  logger.info(`Loaded Endpoint: /api${permissionPath}/:id ========== Method: PUT`);
  logger.info(`Loaded Endpoint: /api${permissionPath}/:id ========== Method: DELETE`);
  logger.info(`Loaded Endpoint: /api${rbacPath}/* ================= Method: GET/POST/PUT/DELETE`);
  logger.info(`Loaded Endpoint: /api${productPath} ================= Method: GET/POST/PUT/DELETE`);
  logger.info("Loaded Endpoint: /api/admin/prodi ================ Method: GET/POST");
  logger.info("Loaded Endpoint: /api/admin/prodi/:id ============= Method: GET/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/prodi/options =============== Method: GET");
  logger.info("Loaded Endpoint: /api/admin/skema ================ Method: GET/POST");
  logger.info("Loaded Endpoint: /api/admin/skema/:id ============= Method: GET/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/skema/options =============== Method: GET");
  logger.info("Loaded Endpoint: /api/admin/bidang-fokus ========= Method: GET/POST");
  logger.info("Loaded Endpoint: /api/admin/bidang-fokus/:id ===== Method: GET/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/bidang-fokus/options ======= Method: GET");
  logger.info(`Loaded Endpoint: /api${tahunAkademikPath} ========== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${tahunAkademikPath}/all ====== Method: GET`);
  logger.info(`Loaded Endpoint: /api${tahunAkademikPath}/:id ====== Method: GET/PUT/DELETE`);
  logger.info(`Loaded Endpoint: /api${outputPath} ================= Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${outputPath}/options ========= Method: GET`);
  logger.info(`Loaded Endpoint: /api${outputPath}/:id ============= Method: GET/PUT/DELETE`);
  logger.info(`Loaded Endpoint: /api${sertifikatMutuPath} ========= Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${sertifikatMutuPath}/all ===== Method: GET`);
  logger.info(`Loaded Endpoint: /api${sertifikatMutuPath}/:id ===== Method: GET/PUT/DELETE`);
  logger.info(`Loaded Endpoint: /api${filesPath}/path/:subdir/:filename = Method: GET`);
  logger.info(`Loaded Endpoint: /api${uploadPath}/image =========== Method: POST/DELETE`);
  logger.info(`Loaded Endpoint: /api${uploadPath}/richtext ======== Method: POST/DELETE`);
  logger.info(`Loaded Endpoint: /api${beritaPath} ================= Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${beritaPath}/:slug =========== Method: GET`);
  logger.info(`Loaded Endpoint: /api${pengumumanPath} ============= Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${panduanPath} ================ Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${publicpagePath} ============= Method: GET`);
  logger.info(`Loaded Endpoint: /api${carouselPath} =============== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${landingSliderPath} ========== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${capaianPath} ================ Method: GET/PUT`);
  logger.info(`Loaded Endpoint: /api${kategoriPublikasiPath} ====== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${publikasiPath} ============== Method: GET`);
  logger.info(`Loaded Endpoint: /api${publikasiPath}/upsert ======= Method: POST`);
  logger.info(`Loaded Endpoint: /api${mitraKerjaRisetPath} ======== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${productRisetPath} =========== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${penghargaanRisetPath} ======= Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${hibahInternalPath} ========== Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${proposalPath} ================ Method: POST`);
  logger.info(`Loaded Endpoint: /api${invitesPath} ================= Method: GET/POST`);
  logger.info(`Loaded Endpoint: /api${notificationPath} ============ Method: GET/PUT`);
  logger.info("Loaded Endpoint: /api/penelitian and /api/usulan-penelitian = Method: GET/POST/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/pengabdian and /api/usulan-pengabdian = Method: GET/POST/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/proposals/:id/{penelitian,pengabdian,jadwal,luaran,rab} = Method: GET/PUT/POST");
  logger.info("Loaded Endpoint: /api/usulan/search-anggota ======= Method: GET");
  logger.info("Loaded Endpoint: /api/proposal-review ============= Method: GET/POST");
  logger.info("Loaded Endpoint: /api/laporan-usulan =============== Method: GET/POST/PUT");
  logger.info("Loaded Endpoint: /api/proposal-final-pdf ============ Method: GET");
  logger.info("Loaded Endpoint: /api/admin/signatures ============== Method: GET/POST/PATCH/DELETE");
  logger.info("Loaded Endpoint: /api/hki and /api/hki-review ======= Method: GET/POST/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/monev and /api/admin/monev ==== Method: GET/POST/PUT/DELETE");
  logger.info("Loaded Endpoint: /api/dashboard and /api/admin/dashboard = Method: GET");
  logger.info("Loaded Endpoint: /api/audit-logs =================== Method: GET");
  logger.info("Loaded Endpoint: /api/admin/usulan ================ Method: GET");
  logger.info("Loaded Endpoint: /api/admin/usulan/import =========== Method: POST");
}
