export const MODULES = {
  AUTH: "auth",
  USER: "user",
  ROLE: "role",
  PERMISSION: "permission",
  PRODUCT: "product",
  PRODI: "prodi",
  SKEMA: "skema",
  BIDANG_FOKUS: "bidang_fokus",
  TAHUN_AKADEMIK: "tahun_akademik",
  OUTPUT: "output",
  SERTIFIKAT_MUTU: "sertifikat_mutu",
  FILES: "files",
  UPLOAD: "upload",
  BERITA: "berita",
  PENGUMUMAN: "pengumuman",
  PANDUAN: "panduan",
  PUBLICPAGE: "publicpage",
  CAROUSEL: "carousel",
  LANDING_SLIDER: "landing_slider",
  CAPAIAN: "capaian",
  KATEGORI_PUBLIKASI: "kategori_publikasi",
  PUBLIKASI: "publikasi",
  MITRA_KERJA_RISET: "mitra_kerja_riset",
  PRODUCT_RISET: "product_riset",
  PENGHARGAAN_RISET: "penghargaan_riset",
  HIBAH_INTERNAL: "hibah_internal",
  PROPOSAL: "proposal",
  PENELITIAN: "penelitian",
  PENGABDIAN: "pengabdian",
  NOTIFICATION: "notification",
  INVITES: "invites",
  PENELITIAN_PROPOSAL: "penelitian_proposal",
  PENGABDIAN_PROPOSAL: "pengabdian_proposal",
  JADWAL_PROPOSAL: "jadwal_proposal",
  LUARAN_PROPOSAL: "luaran_proposal",
  RAB_PROPOSAL: "rab_proposal",
  SEARCH_ANGGOTA: "search_anggota",
  PROPOSAL_REVIEW: "proposal_review",
  LAPORAN_USULAN: "laporan_usulan",
  PROPOSAL_FINAL_PDF: "proposal_final_pdf",
  OFFICIAL_SIGNATURES: "official_signatures",
  HKI: "hki",
  HKI_REVIEW: "hki_review",
  MONEV_PROPOSAL: "monev_proposal",
  MONEV_INTERNAL: "monev_internal",
  DASHBOARD: "dashboard",
  ADMIN_DASHBOARD: "admin_dashboard",
  AUDITLOG: "auditlog",
  BULK_IMPORT: "bulk_import",
} as const;

export type ModuleName = typeof MODULES[keyof typeof MODULES];

export const AUTH_MODULE = MODULES.AUTH;
export const USER_MODULE = MODULES.USER;
export const ROLE_MODULE = MODULES.ROLE;
export const PERMISSION_MODULE = MODULES.PERMISSION;
export const PRODUCT_MODULE = MODULES.PRODUCT;
export const PRODI_MODULE = MODULES.PRODI;
export const SKEMA_MODULE = MODULES.SKEMA;
export const BIDANG_FOKUS_MODULE = MODULES.BIDANG_FOKUS;
export const TAHUN_AKADEMIK_MODULE = MODULES.TAHUN_AKADEMIK;
export const OUTPUT_MODULE = MODULES.OUTPUT;
export const SERTIFIKAT_MUTU_MODULE = MODULES.SERTIFIKAT_MUTU;
export const FILES_MODULE = MODULES.FILES;
export const UPLOAD_MODULE = MODULES.UPLOAD;
export const BERITA_MODULE = MODULES.BERITA;
export const PENGUMUMAN_MODULE = MODULES.PENGUMUMAN;
export const PANDUAN_MODULE = MODULES.PANDUAN;
export const PUBLICPAGE_MODULE = MODULES.PUBLICPAGE;
export const CAROUSEL_MODULE = MODULES.CAROUSEL;
export const LANDING_SLIDER_MODULE = MODULES.LANDING_SLIDER;
export const CAPAIAN_MODULE = MODULES.CAPAIAN;
export const KATEGORI_PUBLIKASI_MODULE = MODULES.KATEGORI_PUBLIKASI;
export const PUBLIKASI_MODULE = MODULES.PUBLIKASI;
export const MITRA_KERJA_RISET_MODULE = MODULES.MITRA_KERJA_RISET;
export const PRODUCT_RISET_MODULE = MODULES.PRODUCT_RISET;
export const PENGHARGAAN_RISET_MODULE = MODULES.PENGHARGAAN_RISET;
export const HIBAH_INTERNAL_MODULE = MODULES.HIBAH_INTERNAL;
export const PROPOSAL_MODULE = MODULES.PROPOSAL;
export const PENELITIAN_MODULE = MODULES.PENELITIAN;
export const PENGABDIAN_MODULE = MODULES.PENGABDIAN;
export const NOTIFICATION_MODULE = MODULES.NOTIFICATION;
export const INVITES_MODULE = MODULES.INVITES;
export const PENELITIAN_PROPOSAL_MODULE = MODULES.PENELITIAN_PROPOSAL;
export const PENGABDIAN_PROPOSAL_MODULE = MODULES.PENGABDIAN_PROPOSAL;
export const JADWAL_PROPOSAL_MODULE = MODULES.JADWAL_PROPOSAL;
export const LUARAN_PROPOSAL_MODULE = MODULES.LUARAN_PROPOSAL;
export const RAB_PROPOSAL_MODULE = MODULES.RAB_PROPOSAL;
export const SEARCH_ANGGOTA_MODULE = MODULES.SEARCH_ANGGOTA;
export const PROPOSAL_REVIEW_MODULE = MODULES.PROPOSAL_REVIEW;
export const LAPORAN_USULAN_MODULE = MODULES.LAPORAN_USULAN;
export const PROPOSAL_FINAL_PDF_MODULE = MODULES.PROPOSAL_FINAL_PDF;
export const OFFICIAL_SIGNATURES_MODULE = MODULES.OFFICIAL_SIGNATURES;
export const HKI_MODULE = MODULES.HKI;
export const HKI_REVIEW_MODULE = MODULES.HKI_REVIEW;
export const MONEV_PROPOSAL_MODULE = MODULES.MONEV_PROPOSAL;
export const MONEV_INTERNAL_MODULE = MODULES.MONEV_INTERNAL;
export const DASHBOARD_MODULE = MODULES.DASHBOARD;
export const ADMIN_DASHBOARD_MODULE = MODULES.ADMIN_DASHBOARD;
export const AUDITLOG_MODULE = MODULES.AUDITLOG;
export const BULK_IMPORT_MODULE = MODULES.BULK_IMPORT;
